disabled_rules: # rule identifiers to exclude from running
#  - colon
#  - comma
#  - control_statement
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - leading_whitespace
  - line_length
  - nesting
  - large_tuple
  - unused_closure_parameter
  - opening_brace
  - operator_whitespace
  - return_arrow_whitespace
#  - statement_position
  - todo
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
  - xctfail_message
  - variable_name_max_length
  - variable_name_min_length
  - variable_name
#included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.

excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
  - Modules

identifier_name:
  min_length: 2

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25

reporter: "xcode"
